import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Fonte local variável
const fredokaLocal = localFont({
  src: './fonts/Fredoka-VariableFont_wdth,wght.ttf',
  variable: '--font-fredoka-local',
});

// Fonte do Google como fallback
const fredokaGoogle = Fredoka({
  subsets: ['latin'],
  variable: '--font-fredoka-google',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredokaLocal.variable} ${fredokaGoogle.variable} font-fredoka antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
